site_name: pwdsim
site_description: A pytorch Pinewood Derby simulator and optimizer
repo_name: pwdsim

theme:
  name: material
  features:
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Track models: tracks.md
  - Examples:
      - Forward model: examples/forward_model.py
  - API reference: api.md

plugins:
  - search
  - mkdocs-jupyter:
      include: ["examples/*.py"]
      execute: true
      include_source: true
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: false
            members_order: source

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
